// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBixRFfleFen7Wx_wYbS1D-mMc6Z6osrWY',
    appId: '1:60789391124:android:85a0c07ac2f63b79a2cc01',
    messagingSenderId: '60789391124',
    projectId: 'shift-it-ab63b',
    databaseURL: 'https://shift-it-ab63b.firebaseio.com',
    storageBucket: 'shift-it-ab63b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-_gfrCjaT1Z6ojh6gZ0exPj80EuzJWw',
    appId: '1:60789391124:ios:a896731b576d9524a2cc01',
    messagingSenderId: '60789391124',
    projectId: 'shift-it-ab63b',
    databaseURL: 'https://shift-it-ab63b.firebaseio.com',
    storageBucket: 'shift-it-ab63b.appspot.com',
    androidClientId: '60789391124-ff7b1sl4a3osabi0bl72g4rfqd0iopsd.apps.googleusercontent.com',
    iosClientId: '60789391124-bovqn4jdbs1cbahmd3951700dnmjrepb.apps.googleusercontent.com',
    iosBundleId: 'com.example.employerTest',
  );

}